DROP TABLE IF EXISTS LOCAL;
DROP SEQUENCE IF EXISTS SQ_LOCAL;
CREATE SEQUENCE SQ_LOCAL;
CREATE TABLE LOCAL(IDLOCAL BIGINT DEFAULT SQ_LOCAL.nextval PRIMARY KEY NOT NULL, DESCRICAO VARCHAR(255) NOT NULL, LATITUDE INT NOT NULL, LONGITUDE INT NOT NULL);